/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BehindRouteImport } from './routes/behind'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as NewsroomRouteImport } from './routes/newsroom'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as PledgesRouteImport } from './routes/pledges'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as Sdg4RouteImport } from './routes/sdg4'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as WorkRouteImport } from './routes/work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BehindRoute = BehindRouteImport.update({
  id: '/behind',
  path: '/behind',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomRoute = NewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const PledgesRoute = PledgesRouteImport.update({
  id: '/pledges',
  path: '/pledges',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const Sdg4Route = Sdg4RouteImport.update({
  id: '/sdg4',
  path: '/sdg4',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/behind': typeof BehindRoute
  '/dashboard': typeof DashboardRoute
  '/investors': typeof InvestorsRoute
  '/newsroom': typeof NewsroomRoute
  '/parents': typeof ParentsRoute
  '/pledges': typeof PledgesRoute
  '/reports': typeof ReportsRoute
  '/sdg4': typeof Sdg4Route
  '/stories': typeof StoriesRoute
  '/teachers': typeof TeachersRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/behind': typeof BehindRoute
  '/dashboard': typeof DashboardRoute
  '/investors': typeof InvestorsRoute
  '/newsroom': typeof NewsroomRoute
  '/parents': typeof ParentsRoute
  '/pledges': typeof PledgesRoute
  '/reports': typeof ReportsRoute
  '/sdg4': typeof Sdg4Route
  '/stories': typeof StoriesRoute
  '/teachers': typeof TeachersRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/behind': typeof BehindRoute
  '/dashboard': typeof DashboardRoute
  '/investors': typeof InvestorsRoute
  '/newsroom': typeof NewsroomRoute
  '/parents': typeof ParentsRoute
  '/pledges': typeof PledgesRoute
  '/reports': typeof ReportsRoute
  '/sdg4': typeof Sdg4Route
  '/stories': typeof StoriesRoute
  '/teachers': typeof TeachersRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/behind'
    | '/dashboard'
    | '/investors'
    | '/newsroom'
    | '/parents'
    | '/pledges'
    | '/reports'
    | '/sdg4'
    | '/stories'
    | '/teachers'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/behind'
    | '/dashboard'
    | '/investors'
    | '/newsroom'
    | '/parents'
    | '/pledges'
    | '/reports'
    | '/sdg4'
    | '/stories'
    | '/teachers'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/behind'
    | '/dashboard'
    | '/investors'
    | '/newsroom'
    | '/parents'
    | '/pledges'
    | '/reports'
    | '/sdg4'
    | '/stories'
    | '/teachers'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BehindRoute: typeof BehindRoute
  DashboardRoute: typeof DashboardRoute
  InvestorsRoute: typeof InvestorsRoute
  NewsroomRoute: typeof NewsroomRoute
  ParentsRoute: typeof ParentsRoute
  PledgesRoute: typeof PledgesRoute
  ReportsRoute: typeof ReportsRoute
  Sdg4Route: typeof Sdg4Route
  StoriesRoute: typeof StoriesRoute
  TeachersRoute: typeof TeachersRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behind': {
      id: '/behind'
      path: '/behind'
      fullPath: '/behind'
      preLoaderRoute: typeof BehindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom': {
      id: '/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof NewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pledges': {
      id: '/pledges'
      path: '/pledges'
      fullPath: '/pledges'
      preLoaderRoute: typeof PledgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdg4': {
      id: '/sdg4'
      path: '/sdg4'
      fullPath: '/sdg4'
      preLoaderRoute: typeof Sdg4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BehindRoute: BehindRoute,
  DashboardRoute: DashboardRoute,
  InvestorsRoute: InvestorsRoute,
  NewsroomRoute: NewsroomRoute,
  ParentsRoute: ParentsRoute,
  PledgesRoute: PledgesRoute,
  ReportsRoute: ReportsRoute,
  Sdg4Route: Sdg4Route,
  StoriesRoute: StoriesRoute,
  TeachersRoute: TeachersRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
